# GAME
game = Game.create(username:"minhee")

# LETTERS
g = Letter.create(name: '1-g', image:'https://github.com/minheekangg/Mod4ProjectBackend/blob/master/app/assets/images/Letters/g.png?raw=true', game_id: game.id, sound: "https://github.com/minheekangg/Mod4ProjectBackend/blob/master/app/assets/images/sound/gSound.m4a?raw=true")
n = Letter.create(name: '2-n', image:'https://github.com/minheekangg/Mod4ProjectBackend/blob/master/app/assets/images/Letters/n.png?raw=true', game_id: game.id, sound: "https://github.com/minheekangg/Mod4ProjectBackend/blob/master/app/assets/images/sound/nSound.m4a?raw=true")
d = Letter.create(name: '3-d', image:'https://github.com/minheekangg/Mod4ProjectBackend/blob/master/app/assets/images/Letters/d.png?raw=true', game_id: game.id, sound: "https://github.com/minheekangg/Mod4ProjectBackend/blob/master/app/assets/images/sound/dSound.m4a?raw=true")
r = Letter.create(name: '4-r', image:'https://github.com/minheekangg/Mod4ProjectBackend/blob/master/app/assets/images/Letters/r.png?raw=true', game_id: game.id, sound: "https://github.com/minheekangg/Mod4ProjectBackend/blob/master/app/assets/images/sound/rSound.m4a?raw=true")
m = Letter.create(name:'5-m', image:'https://github.com/minheekangg/Mod4ProjectBackend/blob/master/app/assets/images/Letters/m.png?raw=true', game_id: game.id, sound: "https://github.com/minheekangg/Mod4ProjectBackend/blob/master/app/assets/images/sound/mSound.m4a?raw=true")
b = Letter.create(name: '6-b', image:'https://github.com/minheekangg/Mod4ProjectBackend/blob/master/app/assets/images/Letters/b.png?raw=true', game_id: game.id, sound: "https://github.com/minheekangg/Mod4ProjectBackend/blob/master/app/assets/images/sound/bSound.m4a?raw=true")
s = Letter.create(name: '7-s', image:'https://github.com/minheekangg/Mod4ProjectBackend/blob/master/app/assets/images/Letters/s.png?raw=true', game_id: game.id, sound: "https://github.com/minheekangg/Mod4ProjectBackend/blob/master/app/assets/images/sound/sSound.m4a?raw=true")
o = Letter.create(name: '8-o', image:'https://github.com/minheekangg/Mod4ProjectBackend/blob/master/app/assets/images/Letters/o.png?raw=true', game_id: game.id, sound: "https://github.com/minheekangg/Mod4ProjectBackend/blob/master/app/assets/images/sound/oSound.m4a?raw=true")
j = Letter.create(name: '9-j', image:'https://github.com/minheekangg/Mod4ProjectBackend/blob/master/app/assets/images/Letters/j.png?raw=true', game_id: game.id, sound: "https://github.com/minheekangg/Mod4ProjectBackend/blob/master/app/assets/images/sound/jSound.m4a?raw=true")
c = Letter.create(name: '10-c', image:'https://github.com/minheekangg/Mod4ProjectBackend/blob/master/app/assets/images/Letters/c.png?raw=true', game_id: game.id, sound: "https://github.com/minheekangg/Mod4ProjectBackend/blob/master/app/assets/images/sound/cSound.m4a?raw=true")
k = Letter.create(name: '11-k', image:'https://github.com/minheekangg/Mod4ProjectBackend/blob/master/app/assets/images/Letters/k.png?raw=true', game_id: game.id, sound: "https://github.com/minheekangg/Mod4ProjectBackend/blob/master/app/assets/images/sound/kSound.m4a?raw=true")
t = Letter.create(name: '12-t', image:'https://github.com/minheekangg/Mod4ProjectBackend/blob/master/app/assets/images/Letters/t.png?raw=true', game_id: game.id, sound: "https://github.com/minheekangg/Mod4ProjectBackend/blob/master/app/assets/images/sound/tSound.m4a?raw=true")
p = Letter.create(name: '13-p', image:'https://github.com/minheekangg/Mod4ProjectBackend/blob/master/app/assets/images/Letters/p.png?raw=true', game_id: game.id, sound: "https://github.com/minheekangg/Mod4ProjectBackend/blob/master/app/assets/images/sound/pSound.m4a?raw=true")
h = Letter.create(name: '14-h', image:'https://github.com/minheekangg/Mod4ProjectBackend/blob/master/app/assets/images/Letters/h.png?raw=true', game_id: game.id, sound: "https://github.com/minheekangg/Mod4ProjectBackend/blob/master/app/assets/images/sound/hSound.m4a?raw=true")
endgame = Letter.create(name:'ENDGAME', image:'http://img.danawa.com/images/descFiles/4/397/3396656_1497000996212.png', game_id: game.id, sound: "https://github.com/minheekangg/Mod4ProjectBackend/blob/master/app/assets/images/sound/hSound.m4a?raw=true")
# WORDS BELOW
word1 = Word.create(name:'b-airplane', image:'https://github.com/minheekangg/Mod4ProjectBackend/blob/master/app/assets/images/Words/b-airplane.png?raw=true', letter_id: b.id)
word2 = Word.create(name:'c-toothbrush', image:'https://github.com/minheekangg/Mod4ProjectBackend/blob/master/app/assets/images/Words/c-toothbrush.png?raw=true', letter_id: c.id)
word3 = Word.create(name:'d-pig', image:'https://github.com/minheekangg/Mod4ProjectBackend/blob/master/app/assets/images/Words/d-pig.png?raw=true', letter_id: d.id)
word4 = Word.create(name:'g-dino', image:'https://github.com/minheekangg/Mod4ProjectBackend/blob/master/app/assets/images/Words/g-dino.png?raw=true', letter_id: g.id)
word5 = Word.create(name:'h-hippo', image:'https://github.com/minheekangg/Mod4ProjectBackend/blob/master/app/assets/images/Words/h-hippo.png?raw=true', letter_id: h.id)
word6 = Word.create(name:'j-bicycle', image:'https://github.com/minheekangg/Mod4ProjectBackend/blob/master/app/assets/images/Words/j-bicycle.png?raw=true', letter_id: j.id)
word7 = Word.create(name:'k-elephant', image:'https://github.com/minheekangg/Mod4ProjectBackend/blob/master/app/assets/images/Words/k-elephant.png?raw=true', letter_id: k.id)
word8 = Word.create(name:'m-rainbow', image:'https://github.com/minheekangg/Mod4ProjectBackend/blob/master/app/assets/images/Words/m-rainbow.png?raw=true', letter_id: m.id)
word9 = Word.create(name:'n-butterfly', image:'https://github.com/minheekangg/Mod4ProjectBackend/blob/master/app/assets/images/Words/n-butterfly.png?raw=true', letter_id: n.id)
word10 = Word.create(name:'o-monkey', image:'https://github.com/minheekangg/Mod4ProjectBackend/blob/master/app/assets/images/Words/o-monkey.png?raw=true', letter_id: o.id)
word11 = Word.create(name:'p-piano', image:'https://github.com/minheekangg/Mod4ProjectBackend/blob/master/app/assets/images/Words/p-piano.png?raw=true', letter_id: p.id)
word12 = Word.create(name:'r-robot', image:'https://github.com/minheekangg/Mod4ProjectBackend/blob/master/app/assets/images/Words/r-robot.png?raw=true', letter_id: r.id)
word13 = Word.create(name:'s-apple', image:'https://github.com/minheekangg/Mod4ProjectBackend/blob/master/app/assets/images/Words/s-apple.png?raw=true', letter_id: s.id)
word14 = Word.create(name:'t-tomato', image:'https://github.com/minheekangg/Mod4ProjectBackend/blob/master/app/assets/images/Words/t-tomato.png?raw=true', letter_id: t.id)
